-- ─────────────────────────────────────────────────────────────────────────────
-- Generated media (§20 image generation). Images are generated by the
-- pipeline and self-hosted (served via /api/media/:id) rather than pushed to
-- external object storage — keeps the Instagram auto-attach path dependency-free.
-- ─────────────────────────────────────────────────────────────────────────────

-- drafts.media_asset_id already exists (001_init.sql) but had no FK; add it now
-- that assets rows are actually populated.
ALTER TABLE assets ADD COLUMN IF NOT EXISTS mime_type TEXT;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS data BYTEA;
